# Generated by Django 5.2 on 2025-04-22 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_number', models.CharField(max_length=50, unique=True)),
                ('sowing_date', models.DateField()),
                ('first_cutting_date', models.DateField(blank=True, null=True)),
                ('second_cutting_date', models.DateField(blank=True, null=True)),
                ('third_cutting_date', models.DateField(blank=True, null=True)),
                ('yield_1', models.DecimalField(blank=True, decimal_places=2, help_text='Yield in kg', max_digits=10, null=True)),
                ('yield_2', models.DecimalField(blank=True, decimal_places=2, help_text='Yield in kg', max_digits=10, null=True)),
                ('yield_3', models.DecimalField(blank=True, decimal_places=2, help_text='Yield in kg', max_digits=10, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tray_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tray Data',
                'verbose_name_plural': 'Tray Data',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'Regular User')], default='user', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
